//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public long id { get; set; }
        public Nullable<long> Flight_Id { get; set; }
        public Nullable<long> Customer_Id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
